-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 15:58:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR` (
  `ROW_IDT` INT NOT NULL AUTO_INCREMENT,
  `PBC_IDT` VARCHAR(5) NOT NULL,
  `PSD` VARCHAR(32) NULL,
  `DAT_CRA` DATETIME NULL,
  `EML` TEXT(100) NULL,
  `IMG_AVT` MEDIUMTEXT NULL,
  `BAN` TINYINT NULL,
  PRIMARY KEY (`ROW_IDT`),
  UNIQUE INDEX `PBC_IDT_UNIQUE` (`PBC_IDT` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROL` (
  `ROW_IDT` INT NOT NULL AUTO_INCREMENT,
  `NAM` VARCHAR(25) NULL,
  `RGT` INT(50) NULL,
  PRIMARY KEY (`ROW_IDT`),
  UNIQUE INDEX `NAM_UNIQUE` (`NAM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_ROL_LNK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_ROL_LNK` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_ROL_LNK` (
  `USR_ROW_IDT` INT NOT NULL,
  `ROL_ROW_IDT` INT NULL,
  PRIMARY KEY (`ROL_ROW_IDT`, `USR_ROW_IDT`),
  INDEX `fk_USR_has_ROL_ROL1_idx` (`ROL_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_ROL_USR_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_ROL_USR`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_ROL_ROL1`
    FOREIGN KEY (`ROL_ROW_IDT`)
    REFERENCES `mydb`.`ROL` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_RPT_USR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_RPT_USR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_RPT_USR` (
  `USR_ROW_IDT` INT NULL,
  `USR_ROW_IDT1` INT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `USR_ROW_IDT1`),
  INDEX `fk_USR_has_USR_USR2_idx` (`USR_ROW_IDT1` ASC) VISIBLE,
  INDEX `fk_USR_has_USR_USR1_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_USR_USR1`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_USR_USR2`
    FOREIGN KEY (`USR_ROW_IDT1`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QST` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QST` (
  `ROW_IDT` INT NOT NULL AUTO_INCREMENT,
  `PBC_IDT` VARCHAR(5) NOT NULL,
  `TTL` VARCHAR(50) NULL,
  `DAT` DATE NULL,
  `CTN` LONGTEXT NULL,
  `VSB` TINYINT NULL,
  PRIMARY KEY (`ROW_IDT`),
  UNIQUE INDEX `PBC_IDT_UNIQUE` (`PBC_IDT` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RSP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RSP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RSP` (
  `ROW_IDT` INT NOT NULL AUTO_INCREMENT,
  `PBC_IDT` VARCHAR(5) NOT NULL,
  `CNT` LONGTEXT NULL,
  `UPV` INT NULL,
  `DNV` INT NULL,
  `VSB` TINYINT NULL,
  PRIMARY KEY (`ROW_IDT`),
  UNIQUE INDEX `PBC_IDT_UNIQUE` (`PBC_IDT` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CMT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CMT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CMT` (
  `ROW_IDT` INT NOT NULL AUTO_INCREMENT,
  `PBC_IDT` VARCHAR(5) NOT NULL,
  `CNT` LONGTEXT NULL,
  PRIMARY KEY (`ROW_IDT`),
  UNIQUE INDEX `PBC_IDT_UNIQUE` (`PBC_IDT` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CMT_HAS_CMT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CMT_HAS_CMT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CMT_HAS_CMT` (
  `CMT_ROW_IDT` INT NOT NULL,
  `CMT_ROW_IDT1` INT NULL,
  PRIMARY KEY (`CMT_ROW_IDT`, `CMT_ROW_IDT1`),
  INDEX `fk_CMT_has_CMT_CMT2_idx` (`CMT_ROW_IDT1` ASC) VISIBLE,
  INDEX `fk_CMT_has_CMT_CMT1_idx` (`CMT_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_CMT_has_CMT_CMT1`
    FOREIGN KEY (`CMT_ROW_IDT`)
    REFERENCES `mydb`.`CMT` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CMT_has_CMT_CMT2`
    FOREIGN KEY (`CMT_ROW_IDT1`)
    REFERENCES `mydb`.`CMT` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RSP_CMT_LNK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RSP_CMT_LNK` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RSP_CMT_LNK` (
  `RSP_ROW_IDT` INT NULL,
  `CMT_ROW_IDT` INT NOT NULL,
  PRIMARY KEY (`RSP_ROW_IDT`, `CMT_ROW_IDT`),
  INDEX `fk_RSP_has_CMT_CMT1_idx` (`CMT_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_RSP_has_CMT_RSP1_idx` (`RSP_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_RSP_has_CMT_RSP1`
    FOREIGN KEY (`RSP_ROW_IDT`)
    REFERENCES `mydb`.`RSP` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RSP_has_CMT_CMT1`
    FOREIGN KEY (`CMT_ROW_IDT`)
    REFERENCES `mydb`.`CMT` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QST_RSP_LNK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QST_RSP_LNK` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QST_RSP_LNK` (
  `QST_ROW_IDT` INT NOT NULL,
  `RSP_ROW_IDT` INT NOT NULL,
  PRIMARY KEY (`QST_ROW_IDT`, `RSP_ROW_IDT`),
  INDEX `fk_QST_has_RSP_RSP1_idx` (`RSP_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_QST_has_RSP_QST1_idx` (`QST_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_QST_has_RSP_QST1`
    FOREIGN KEY (`QST_ROW_IDT`)
    REFERENCES `mydb`.`QST` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QST_has_RSP_RSP1`
    FOREIGN KEY (`RSP_ROW_IDT`)
    REFERENCES `mydb`.`RSP` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_WRT_QST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_WRT_QST` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_WRT_QST` (
  `USR_ROW_IDT` INT NULL,
  `QST_ROW_IDT` INT NOT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `QST_ROW_IDT`),
  INDEX `fk_USR_has_QST_QST1_idx` (`QST_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_QST_USR1_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_QST_USR1`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_QST_QST1`
    FOREIGN KEY (`QST_ROW_IDT`)
    REFERENCES `mydb`.`QST` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_RPT_QST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_RPT_QST` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_RPT_QST` (
  `USR_ROW_IDT` INT NULL,
  `QST_ROW_IDT` INT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `QST_ROW_IDT`),
  INDEX `fk_USR_has_QST_QST2_idx` (`QST_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_QST_USR2_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_QST_USR2`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_QST_QST2`
    FOREIGN KEY (`QST_ROW_IDT`)
    REFERENCES `mydb`.`QST` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_WRT_RSP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_WRT_RSP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_WRT_RSP` (
  `USR_ROW_IDT` INT NULL,
  `RSP_ROW_IDT` INT NOT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `RSP_ROW_IDT`),
  INDEX `fk_USR_has_RSP_RSP1_idx` (`RSP_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_RSP_USR1_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_RSP_USR1`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_RSP_RSP1`
    FOREIGN KEY (`RSP_ROW_IDT`)
    REFERENCES `mydb`.`RSP` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_RPT_RSP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_RPT_RSP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_RPT_RSP` (
  `USR_ROW_IDT` INT NULL,
  `RSP_ROW_IDT` INT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `RSP_ROW_IDT`),
  INDEX `fk_USR_has_RSP_RSP2_idx` (`RSP_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_RSP_USR2_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_RSP_USR2`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_RSP_RSP2`
    FOREIGN KEY (`RSP_ROW_IDT`)
    REFERENCES `mydb`.`RSP` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_WRT_CMT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_WRT_CMT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_WRT_CMT` (
  `USR_ROW_IDT` INT NULL,
  `CMT_ROW_IDT` INT NOT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `CMT_ROW_IDT`),
  INDEX `fk_USR_has_CMT_CMT1_idx` (`CMT_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_CMT_USR1_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_CMT_USR1`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_CMT_CMT1`
    FOREIGN KEY (`CMT_ROW_IDT`)
    REFERENCES `mydb`.`CMT` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USR_RPT_CMT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USR_RPT_CMT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USR_RPT_CMT` (
  `USR_ROW_IDT` INT NULL,
  `CMT_ROW_IDT` INT NULL,
  PRIMARY KEY (`USR_ROW_IDT`, `CMT_ROW_IDT`),
  INDEX `fk_USR_has_CMT1_CMT1_idx` (`CMT_ROW_IDT` ASC) VISIBLE,
  INDEX `fk_USR_has_CMT1_USR1_idx` (`USR_ROW_IDT` ASC) VISIBLE,
  CONSTRAINT `fk_USR_has_CMT1_USR1`
    FOREIGN KEY (`USR_ROW_IDT`)
    REFERENCES `mydb`.`USR` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USR_has_CMT1_CMT1`
    FOREIGN KEY (`CMT_ROW_IDT`)
    REFERENCES `mydb`.`CMT` (`ROW_IDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
